version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-dockerhub-username/pijar-food-mobile:dev
    ports:
      - "8081:8081"   # Metro
      - "19000:19000" # expo dev
      - "19001:19001"
      - "19002:19002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
